import type { Metadata } from "next";
import Header from "@/app/component/Header";
import Footer from "@/app/component/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja">
      <body className="container mx-auto bg-slate-700 text-slate-50">
        {" "}
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
